### PR TITLE
Added nuspec and migration pcl to .net standard

### PR DESCRIPTION
**Pull request by LeoJHarris**
Have added nuspec and migration to .net standard 2.0. Needs to be built and tested on iOS to ensure the FormsControl.Touch is being included in the nuget package for iOS.

Resolved obsolete AppCompatAnimationNavRenderer constructor causing exception Android.Content.Res.Resources+NotFoundException: Resource ID #0x7f0a000d

### CODE REVIEW

**Comment by LeoJHarris** [comment]
Please run past changes made, let me know if any issues exist.

**Comment by LeoJHarris** [comment]
Crash report that was resolved in the AppCompatAnimationNavRenderer.
[Exception animation navigation.txt](https://github.com/AlexandrNikulin/AnimationNavigationPage/files/1873625/Exception.animation.navigation.txt)

**Comment by AlexandrNikulin** [comment]
I will check it ASAP. Thanks

**Comment by AlexandrNikulin** [comment]
@LeoJHarris  Please next time create branch in my  repo and create pull-request to master from this branch.

**Pull request merged**
