### PR TITLE
Fix for swipe back issue  to blank page issue

### PR DESCRIPTION
**Pull request by pmahend1**
Fix for swipe back issue. Please test

### CODE REVIEW

**Comment by pmahend1** [comment]
#61 

#62 

#44 
Fixes these

**Comment by AlexandrNikulin** [comment]
@pmahend1  Thanks! I will update nuget package to tonight

**Comment by pmahend1** [comment]
@AlexandrNikulin I modified and pushed nuget with name [Xamarin.Forms.AnimationNavigation](https://www.nuget.org/packages/Xamarin.Forms.AnimationNavigation/)

**Comment by AlexandrNikulin** [comment]
@pmahend1 yes I see. Ok, this is your choice, but I think no need for this, because I will update original nuget package tonight

**Comment by AlexandrNikulin** [comment]
@pmahend1 And thanks a lot for your pull-request!

**Comment by AlexandrNikulin** [comment]
@pmahend1 Oh, i had issue with my VS for mac after merge this pull-request "Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/5.0.0/index.json." =(

I will update nuget later

**Comment by AlexandrNikulin** [comment]
Found solution and updated nuget package

**Comment by pmahend1** [comment]
@AlexandrNikulin
Probably because I had changed nuget Id. Seems you used nuget push from command line.

**Comment by AlexandrNikulin** [comment]
@pmahend1 yes, I use command line. Anyway I uploaded nuget package with your fixes and add you as Author.

**Pull request merged**
